In [ ]:
l=input().split()
l=list(map(int,l))
s=len(l1)
i=0
for i in range(s):
    if((l1[i]%3==0)or(l1[i]%5==0)or(l1[i]%7==0)):
        print(l1[i])


# DATA SCIENCE
## NUMPY-NUMERICAL PYTHON
### PANDAS - DATAFRAMES AND SERIES
### MATPLOTLIB-VISUALIZATION
### SEABORN-MAKES DIFFICULT TASK EASY
###  INTERACTIVE PYTHON(IPTTHON)


In [1]:
import numpy as np
a =  np.array([1,2,3,4])
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

In [2]:
li=[1,3,5,7]
l_a=np.array(li)
print(l_a)

[1 3 5 7]


# ndim:returns the dimension of the array
## shape:returns the length of the array
## size:size of an array
## itemsize:returns the size of an eleement
## dtype:returns the type of an array

In [6]:
import numpy as np
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
n=np.random.randint(0,50,10)
print(n)
print(n.ndim)
print(n.shape)
print(n.size)
print(n.itemsize)
print(n.dtype)



[ 2 18  1  4  5 43 28  6  3  3]
1
(10,)
10
4
int32


In [11]:
n=np.random.randint(0,50,size=12).reshape(3,4)
print(n)
print(n.ndim)# returns no.of dimensions
n[::-1]#reverse the array

[[32  9 36 24]
 [32 24 16 49]
 [ 0 43 19 27]]
2


array([[ 0, 43, 19, 27],
       [32, 24, 16, 49],
       [32,  9, 36, 24]])

In [15]:
n=np.ones(9,type=int)
m=np.zeros(8)
print(n)
print(m)

TypeError: ones() got an unexpected keyword argument 'type'

In [40]:
k=np.linspace(0,2,9)
print(k)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [18]:
f=np.full((2,2),9)
f

array([[9, 9],
       [9, 9]])

In [19]:
em=np.empty((5,2))
em

array([[1.29441743e-312, 2.37663529e-312],
       [2.16443571e-312, 2.29175545e-312],
       [8.48798317e-313, 1.06099790e-312],
       [1.06099790e-312, 9.33678148e-313],
       [8.70018275e-313, 2.16443571e-312]])

In [22]:
em=np.empty(5)
print(em)

[3.81959242e-313 8.48798316e-314 9.12458190e-313 1.27319748e-313
 6.36598737e-314]


In [23]:
c=np.array([[[2,4,5],[9,10,4]]])
c
c.ndim
c.reshape(1,6)

array([[ 2,  4,  5,  9, 10,  4]])

In [26]:
c.ravel()

array([ 2,  4,  5,  9, 10,  4])

In [33]:
a=22
b=56
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sin(a))
print(np.sqrt(100))
print(np.cos(b))
print(np.exp(64))
print(np.log(4))



78
-34
1232
0.39285714285714285
-0.008851309290403876
10.0
0.853220107722584
6.235149080811617e+27
1.3862943611198906


In [39]:
a=np.arange(18).reshape(3,6)
print(a)
print("max",a.max())
print("min",a.min(axis=0))
print(a.max(axis=1))
print("sum",a.sum())
print("mean",a.mean())
print("median",np.median(a))
print(np.std(b))


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
max 17
min [0 1 2 3 4 5]
[ 5 11 17]
sum 153
mean 8.5
median 8.5
0.0


In [37]:
a.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153], dtype=int32)

In [4]:
import numpy as np
sa = np.array([23,45,98,1,2,3,4])
sa.sort()

In [5]:
sa

array([ 1,  2,  3,  4, 23, 45, 98])

In [8]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("transpose \n",np.transpose(s))
s.T

transpose 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
print(np.hsplit(s,3))   #horizontal split

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [10]:
print(np.vsplit(s,3))   #vertical split

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [13]:
sa=np.array([1,2,3,4,5,6,7,8,9])
np.hsplit(sa,3)


[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [14]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
s[0]

array([1, 2, 3])

In [15]:
print(s[0:2])

[[1 2 3]
 [4 5 6]]


In [17]:
s[0:3,1]

array([2, 5, 8])

In [18]:
s[2,0]

7

In [23]:

s1=np.arange(1,50)
s1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
s.sum


<function ndarray.sum>

AttributeError: module 'numpy' has no attribute 'csum'